; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
	platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
	platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip
board = waveshare_esp32s3_touch_lcd_4_3
framework = arduino

monitor_port = COM3
monitor_speed = 115200
monitor_filters =
	esp32_exception_decoder
	colorize
upload_speed = 921600

build_unflags =
	-std=gnu++17
build_src_filter =
	+<*>
	-<old/*>
	-<hardware/*>

lib_deps =
	https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
	https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
	https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
	https://github.com/lvgl/lvgl.git#v8.4.0
	https://github.com/bakercp/CRC32.git#2.0.0
	bblanchon/ArduinoJson@^7.4.1
	; adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	; thomasfredericks/Bounce2@^2.72

[env:Release]
build_flags =
	-D CORE_DEBUG_LEVEL=1
	-D DISABLE_ALL_LIBRARY_WARNINGS
	${common.build_flags}

[env:Debug]
build_flags =
	-D CORE_DEBUG_LEVEL=4
	${common.build_flags}

[common]
build_flags =
	-std=gnu++2a
	-I src
	-D VERSION=\"v1.0.0\"

	-D ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-D BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_4_3
	-DLV_COLOR_16_SWAP=0
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_LVGL_H_INCLUDE_SIMPLE

	-D CFG_TUD_VENDOR_NAME="Lucyd"
	-D CFG_TUD_PRODUCT_NAME="LucydDeck"
	-D I2C_MASTER_NUM=I2C_NUM_0
	-D I2C_MASTER_SDA_IO=8
	-D I2C_MASTER_SCL_IO=9
	-D SD_MOSI=11
	-D SD_CLK=12
	-D SD_MISO=13
	-D SD_CS=4
	-D USB_SEL=5
	-D SD_SS=-1

	-D CONFIG_DISABLE_HAL_LOCKS=1
	-D CONFIG_FREERTOS_UNICORE=1
	-D CONFIG_BTDM_CTRL_MODE_BTDM=0
	-D CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=0
	-D CONFIG_BTDM_CTRL_MODE_BLE_ONLY=0
	-D CONFIG_BTDM_CTRL_MODE_IDLE=1
	-D CONFIG_WIFI_ENABLED=0
