[env]
framework = arduino
board = waveshare_esp32s3_touch_lcd_4_3
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
	platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
	; Use high performance libraries to improve the performance, and avoid esp32s3 RGB LCD screen drifting issue
	platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip

upload_speed = 921600
upload_flags =
    --after=no_reset
monitor_speed = 115200
monitor_filters =
	esp32_exception_decoder
	time

build_unflags =
	-std=gnu++17
build_src_filter =
	+<*>
extra_scripts = pre:version_script.py

lib_deps =
	https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
	https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
	https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
	https://github.com/lvgl/lvgl.git#v8.4.0
	bakercp/CRC32@2.0.1
	bblanchon/ArduinoJson@7.4.2

[common]
build_flags =
	-std=gnu++2b
	-I src
	-D PROTOCOL_VERSION=1
	-D BOARD_NAME=\"WAVESHARE_ESP32_S3_TOUCH_LCD_4_3\"

	-D ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
	-D BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_4_3

	-D LV_COLOR_16_SWAP=0
	-D LV_CONF_PATH="display/lvgl/lv_conf.h"
	-D LV_LVGL_H_INCLUDE_SIMPLE

[env:release]
build_type = release
build_flags =
	-D CORE_DEBUG_LEVEL=1
	-D DISABLE_ALL_LIBRARY_WARNINGS
	-D ESP_UTILS_CONF_LOG_LEVEL=ESP_UTILS_LOG_LEVEL_ERROR
	${common.build_flags}

[env:debug]
build_type = debug
build_flags =
	-D CORE_DEBUG_LEVEL=4
	-D ESP_UTILS_CONF_LOG_LEVEL=ESP_UTILS_LOG_LEVEL_INFO
	-D LVGL_PORT_ENABLE_PERF_MONITOR=1
	${common.build_flags}
